# Generated by Django 4.2.7 on 2024-01-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='banner',
            field=models.CharField(default='/room/images/room.jpg', max_length=200),
        ),
    ]
