# Generated by Django 4.2.7 on 2023-12-06 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARITIALLY_PAID', 'Partially Paid'), ('FULLY_PAID', 'Fully Paid'), ('DEPOSIT', 'Deposit')], default='UNPAID', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('services', models.ManyToManyField(to='room.service')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CREDIT', 'Credit'), ('CASH', 'Cash')], max_length=20)),
                ('note', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
