# Generated by Django 4.2.7 on 2023-12-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_service_status'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rooms',
            field=models.ManyToManyField(to='room.room'),
        ),
    ]
